
<!-- End Page Content -->
          <!--Begin Footer-->
        </div>
      </div>
      <!-- Put Any footer related info below this line-->
      <table style="width:100%;">
        <tr>
          <td>
            <center>
              <span id="cms_footer">
                <?=Config::COPYRIGHT?>
              </span>
            </center>
          </td>
        </td>
      </table>
    </div>
    <center>
      <table cellpadding="5" style="margin-top:10px;margin-bottom:10px;">
        <tr>
          <td>
            <span style="font-size:12px; color:#FFFFFF;">- <?=Config::APP_NAME?> -</span>
          </td>
        </td>
      </table>
    </center>
  </body>
</html>
