<!DOCTYPE html>
<html>
  <!-- UI Container Page-->
  <head>
    <title><?=$styleTitle?></title>
    <link href="<?=Config::APP_ROOT?>/inc/style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
  <div id="cms_body_div">
    <div style="background:white;width:100%;margin-bottom:20px;">
      <table style="background:url('<?=Config::APP_ROOT?>/pixmaps/header.png'); background-repeat: repeat-x; width:100%; height:68;" >
        <tr>
          <td>
            <img src="<?=Config::APP_ROOT?>/pixmaps/logo.png"/>
          </td>
          <td>
            <!-- Menu goes here -->
          </td>
        </tr>
      </table>
    <div style="margin-left:50px;margin-right:50px;">

<!-- Begin Page Content -->
